### PR TITLE
Update mips.tmLanguage

### PR DESCRIPTION
**Pull request by biopuppet**
Add subi

### CODE REVIEW

**Comment by kdarkhan** [comment]
@Gone157 I believe there is no `subi` instruction in MIPS.
You can check https://stackoverflow.com/questions/6918306/why-doesnt-there-exists-a-subi-opcode-for-mips for reference.
I will close the PR if you agree.

**Comment by Gone157** [comment]
Thank you!
I was aware of that. And I totally agree.
It's just `subi` is the only extended instruction I used in most of my programs and I feel it's kinda odd to have this single instruction non-highlighted. 😂

**Comment by kdarkhan** [comment]
Ok, I see it is a pseudoinstruction and used at least somewhere.
If you need this, I can still merge it.

**Comment by Gone157** [comment]
Nah, it's fine. No big deal.
Thanks!

**Comment by akainth015** [comment]
I would like to have it, if it's possible to reopen this pull request.

**Comment by kdarkhan** [comment]
@akainth015,

I just merged the PR and re-published the extension at version 0.0.7.

**Comment by akainth015** [comment]
That was fast - thank you so much

**Pull request merged**
