### PR TITLE
Update snippets.json

### PR DESCRIPTION
**Pull request by saikumarmk**
Credit to Rupert

### CODE REVIEW

**Comment by saikumarmk** [comment]
FYI:

print string syscall code was incorrectly set to 1 when it was meant to be 4

**Comment by kdarkhan** [comment]
Thanks for the fix. While you are here, can you also adjust `print1` and `print3`?

**Comment by saikumarmk** [comment]
Do you mean `print1` and `print2`, which should be changed to loading in `$f12`? I'd also change the name of the other print snippets from `print1` to `printDouble`.

**Comment by kdarkhan** [comment]
I meant just renaming `print1` to `print3` and `print3` to `print1`. That seemed to be more reasonable since they `li` `3` and `1` respectively. I don't use snippets that often so maybe I am missing some context.

**Comment by saikumarmk** [comment]
I personally think renaming the snippets to printInt over print1 is more descriptive for those who do not remember which syscall code corresponds to which.

**Comment by kdarkhan** [comment]
Thanks, sounds good.

**Pull request merged**
